// Mocks generated by Mockito 5.4.4 from annotations
// in capoeirasport_project/test/src/features/news_and_events/events/data/repos/event_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:capoeirasport_project/core/utils/network_info.dart' as _i6;
import 'package:capoeirasport_project/src/features/news_and_events/events/data/datasources/event_local_data_source.dart'
    as _i5;
import 'package:capoeirasport_project/src/features/news_and_events/events/data/datasources/event_remote_data_sources.dart'
    as _i2;
import 'package:capoeirasport_project/src/features/news_and_events/events/data/models/event_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EventRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRemoteDataSource extends _i1.Mock
    implements _i2.EventRemoteDataSource {
  MockEventRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.EventModel>> getEventList() => (super.noSuchMethod(
        Invocation.method(
          #getEventList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.EventModel>>.value(<_i4.EventModel>[]),
      ) as _i3.Future<List<_i4.EventModel>>);
}

/// A class which mocks [EventLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventLocalDataSource extends _i1.Mock
    implements _i5.EventLocalDataSource {
  MockEventLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.EventModel>> getLastEventList() => (super.noSuchMethod(
        Invocation.method(
          #getLastEventList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.EventModel>>.value(<_i4.EventModel>[]),
      ) as _i3.Future<List<_i4.EventModel>>);

  @override
  _i3.Future<void> cacheEventList(List<_i4.EventModel>? eventListToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheEventList,
          [eventListToCache],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
