// Mocks generated by Mockito 5.4.4 from annotations
// in capoeirasport_project/test/src/features/news_and_events/events/data/repos/event_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:capoeirasport_project/core/common/datasources/common_local_data_sources.dart'
    as _i6;
import 'package:capoeirasport_project/core/common/repository/common_remote_repository.dart'
    as _i4;
import 'package:capoeirasport_project/core/network/dio_client.dart' as _i2;
import 'package:capoeirasport_project/core/network/network_info.dart' as _i8;
import 'package:capoeirasport_project/core/utils/hive_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDioClient_0 extends _i1.SmartFake implements _i2.DioClient {
  _FakeDioClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommonRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommonRemoteRepository<T> extends _i1.Mock
    implements _i4.CommonRemoteRepository<T> {
  MockCommonRemoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DioClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeDioClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.DioClient);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  T fromJson(Map<String, dynamic>? json) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _i5.dummyValue<T>(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as T);

  @override
  Map<String, dynamic> toJson(T? body) => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [body],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<List<T>> getListOfThings() => (super.noSuchMethod(
        Invocation.method(
          #getListOfThings,
          [],
        ),
        returnValue: _i3.Future<List<T>>.value(<T>[]),
      ) as _i3.Future<List<T>>);

  @override
  _i3.Future<T> getThing({required int? id}) => (super.noSuchMethod(
        Invocation.method(
          #getThing,
          [],
          {#id: id},
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #getThing,
                  [],
                  {#id: id},
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #getThing,
                [],
                {#id: id},
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> postThing({required T? body}) => (super.noSuchMethod(
        Invocation.method(
          #postThing,
          [],
          {#body: body},
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #postThing,
                  [],
                  {#body: body},
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #postThing,
                [],
                {#body: body},
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> putThing({
    required int? id,
    required T? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putThing,
          [],
          {
            #id: id,
            #body: body,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #putThing,
                  [],
                  {
                    #id: id,
                    #body: body,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #putThing,
                [],
                {
                  #id: id,
                  #body: body,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<void> deleteThing({required int? id}) => (super.noSuchMethod(
        Invocation.method(
          #deleteThing,
          [],
          {#id: id},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [CommonLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommonLocalDataSource<TypeModel> extends _i1.Mock
    implements _i6.CommonLocalDataSource<TypeModel> {
  MockCommonLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.BoxType get boxType => (super.noSuchMethod(
        Invocation.getter(#boxType),
        returnValue: _i7.BoxType.newsList,
      ) as _i7.BoxType);

  @override
  _i3.Future<List<TypeModel>> getLastTypeModelList() => (super.noSuchMethod(
        Invocation.method(
          #getLastTypeModelList,
          [],
        ),
        returnValue: _i3.Future<List<TypeModel>>.value(<TypeModel>[]),
      ) as _i3.Future<List<TypeModel>>);

  @override
  _i3.Future<void> cacheTypeModelList(List<TypeModel>? typeModelListToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTypeModelList,
          [typeModelListToCache],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
